mybatis:
  type-aliases-package: org.strawberry.demo1.model
  mapper-locations: classpath:mappers/*.xml
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/caomei?serverTimezone=UTC
    username: root
    password: root